name: POC Python

on:
  push:
    branches:
      - main

jobs:
    python-script:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        steps:

            - name: checkout repo content
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                pip install browser-use

            - name: Print API Key
              run: echo "OPENAI_API_KEY=$OPENAI_API_KEY"

            - name: Run Python Script
              run: |
                python scripts/main.py

            